/* 라이트 모드 */
export const lightTheme = {
    color: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        font: "var(--color-font)",
        fontWhite: "var(--color-font-white)",
        fontGray: "var(--color-font-gray)",
        fontDeactivate: "var(--color-font-deactivate)",
        inputBg: "var(--color-input-bg)",
        inputIcon: "var(--color-input-icon)",
        placeholderGray: "var(--color-placeholder-gray)",
        borderGray: "var(--color-border-gray)",
        loginTitle: "var(--color-login-title)",
        buttonBg: "var(--color-button-bg)",
        background: "var(--color-background)",
        navBg: "var(--color-nav-bg)",
        navGray: "var(--color-nav-gray)",
        outboxBg: "var(--color-outbox-bg)",
        insideboxBg: "var(--color-insidebox-bg)",
        state: "var(--color-state)",
        tab1: "var(--color-status-tab1)",
        tab2: "var(--color-status-tab2)",
        tab3: "var(--color-status-tab3)",
        tab4: "var(--color-status-tab4)",
        red: "var(--color-red)",
        blue: "var(--color-blue)",
        calenderHeader: "var(--color-calender-header)",
        modalBackground: "var(--color-modal-background)",
        modalContentBg: "var(--color-modal-content-background)",
        modalTagBg: "var(--color-modal-tag-background)",
    },
};

/* 다크 모드 */
export const darkTheme = {
    color: {
        primary: "var(--color-dark-primary)",
        secondary: "var(--color-dark-secondary)",
        font: "var(--color-dark-font)",
        fontWhite: "var(--color-dark-font-white)",
        fontGray: "var(--color-dark-font-gray)",
        fontDeactivate: "var(--color-dark-font-deactivate)",
        inputBg: "var(--color-dark-input-bg)",
        inputIcon: "var(--color-dark-input-icon)",
        placeholderGray: "var(--color-dark-placeholder-gray)",
        borderGray: "var(--color-dark-border-gray)",
        loginTitle: "var(--color-dark-login-title)",
        buttonBg: "var(--color-dark-button-bg)",
        background: "var(--color-dark-background)",
        navBg: "var(--color-dark-nav-bg)",
        navGray: "var(--color-dark-nav-gray)",
        outboxBg: "var(--color-dark-outbox-bg)",
        insideboxBg: "var(--color-dark-insidebox-bg)",
        state: "var(--color-dark-state)",
        tab1: "var(--color-dark-status-tab1)",
        tab2: "var(--color-dark-status-tab2)",
        tab3: "var(--color-dark-status-tab3)",
        tab4: "var(--color-dark-status-tab4)",
        red: "var(--color-dark-red)",
        blue: "var(--color-dark-blue)",
        calenderHeader: "var(--color-dark-calender-header)",
        modalBackground: "var(--color-dark-modal-background)",
        modalContentBg: "var(--color-dark-modal-content-background)",
        modalTagBg: "var(--color-dark-modal-tag-background)",
    },
};
